export const AUTH_USER_REPOSITORY = Symbol('AUTH_USER_REPOSITORY');

export const PASSWORD_HASHER_SERVICE = Symbol('PASSWORD_HASHER_SERVICE');

export const ACCESS_TOKEN_SERVICE = Symbol('ACCESS_TOKEN_SERVICE');
