export const RESOLUCION_DIAN_REPOSITORY = Symbol('RESOLUCION_DIAN_REPOSITORY');
export const CLIENTE_DIAN_REPOSITORY = Symbol('CLIENTE_DIAN_REPOSITORY');
export const FACTURA_ELECTRONICA_REPOSITORY = Symbol(
  'FACTURA_ELECTRONICA_REPOSITORY',
);
export const RAZON_SOCIAL_DIAN_REPOSITORY = Symbol(
  'RAZON_SOCIAL_DIAN_REPOSITORY',
);
